import type { Metadata } from "next";
import { Geist, Geist_Mono, PT_Sans_Narrow } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const narrowFont = PT_Sans_Narrow({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-narrow",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${narrowFont.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
